### ISSUE TITLE
Concurrent Modification Error

### ISSUE THREAD

**Issue by nicholasveronico** [Treasure-Inc/Treasure-Particles#1]
Hello!

Using the latest trElytra jar, we are presented with a ConcurrentModificationException error:

`[22:52:37 WARN]: [TrElytra] Plugin TrElytra v1.3.0 generated an exception while executing task 27
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1630) ~[?:?]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1628) ~[?:?]
        at net.treasure.effect.task.EffectsTask.run(EffectsTask.java:19) ~[TrElytra.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.19.3.jar:git-Pufferfish-52]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[pufferfish-1.19.3.jar:git-Pufferfish-52]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[pufferfish-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

Thank you in advance.

**Comment by zypec** [comment]
I apologize for the late response. If you could share with us how you encountered the error, it would be easier for us to understand the problem.

**Comment by nicholasveronico** [comment]
> I apologize for the late response. If you could share with us how you encountered the error, it would be easier for us to understand the problem.

It happens randomly. I assume it's a repeated task that's causing it to error periodically.
